# Generated by Django 3.2.18 on 2023-02-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smarthome',
            name='plug',
            field=models.CharField(default='OFF', max_length=100),
            preserve_default=False,
        ),
    ]
